name: E2E-Tests

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["CI-Tests"]
    types:
      - completed


jobs:

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Use Node.js 12 for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '12.22.0'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn --frozen-lockfile
      
      - name: Install dependencies
        working-directory: ./backend
        run: yarn --frozen-lockfile

      - name: Start Frontend
        working-directory: ./frontend
        run: yarn start &  # Run in background
      
      - name: Start Backend
        working-directory: ./backend
        run: yarn start &  # Run in background

      - name: Wait for Backend to be Ready
        run: |
          echo "Waiting for backend to start..."
          sleep 10  # Adjust this as needed

      - name: Run Cypress E2E Tests
        working-directory: ./frontend
        run: yarn cypress run --headless --browser chrome
