name: CI-Tests

on: [push, workflow_dispatch]


jobs:
  backend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12.0'
      
      - name: Install dependencies
        working-directory: ./backend
        run: yarn --frozen-lockfile
      
      - name: Run tests
        working-directory: ./backend
        run: yarn test

  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12.0'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: yarn --frozen-lockfile
      
      - name: Run tests
        working-directory: ./frontend
        run: yarn test
